export const COMMON = {
  outline: "outline outline-offset-1",
  hoverOutline: "hover:outline hover:outline-offset-2",
  placeholder: "placeholder:font-regular",
  focusOutline: "focus:outline focus:outline-offset-2",
};
export const COLOR_THEME = {
  RED: {
    label: "Red",
    bgColor: "bg-red-600",
    lightBgColor: "bg-red-50",
    textColor: "text-red-50",
    hoverBgColor: "hover:bg-red-500",
    outline: `${COMMON.outline} outline-red-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-red-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-red-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-red-500`,
    scrollbar: `scrollbar scrollbar-red`,
  },
  STONE: {
    label: "Stone",
    bgColor: "bg-stone-800",
    lightBgColor: "bg-stone-50",
    textColor: "text-stone-50",
    hoverBgColor: "hover:bg-stone-700",
    outline: `${COMMON.outline} outline-stone-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-stone-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-stone-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-stone-500`,
    scrollbar: `scrollbar scrollbar-stone`,
  },
  BLUE: {
    label: "Blue",
    bgColor: "bg-blue-700",
    lightBgColor: "bg-blue-50",
    textColor: "text-blue-50",
    hoverBgColor: "hover:bg-blue-600",
    outline: `${COMMON.outline} outline-blue-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-blue-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-blue-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-blue-500`,
    scrollbar: `scrollbar scrollbar-blue`,
  },
  PINK: {
    label: "Pink",
    bgColor: "bg-pink-600",
    lightBgColor: "bg-pink-50",
    textColor: "text-pink-50",
    hoverBgColor: "hover:bg-pink-700",
    outline: `${COMMON.outline} outline-pink-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-pink-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-pink-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-pink-500`,
    scrollbar: `scrollbar scrollbar-pink`,
  },
  PURPLE: {
    label: "Purple",
    bgColor: "bg-purple-600",
    lightBgColor: "bg-purple-50",
    textColor: "text-purple-50",
    hoverBgColor: "hover:bg-purple-700",
    outline: `${COMMON.outline} outline-purple-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-purple-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-purple-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-purple-500`,
    scrollbar: `scrollbar scrollbar-purple`,
  },
  INDIGO: {
    label: "Indigo",
    bgColor: "bg-indigo-600",
    lightBgColor: "bg-indigo-50",
    textColor: "text-indigo-50",
    hoverBgColor: "hover:bg-indigo-700",
    outline: `${COMMON.outline} outline-indigo-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-indigo-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-indigo-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-indigo-500`,
    scrollbar: `scrollbar scrollbar-indigo`,
  },
  CYAN: {
    label: "Cyan",
    bgColor: "bg-cyan-600",
    lightBgColor: "bg-cyan-50",
    textColor: "text-cyan-50",
    hoverBgColor: "hover:bg-cyan-700",
    outline: `${COMMON.outline} outline-cyan-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-cyan-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-cyan-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-cyan-500`,
    scrollbar: `scrollbar scrollbar-cyan`,
  },
  TEAL: {
    label: "Teal",
    bgColor: "bg-teal-600",
    lightBgColor: "bg-teal-50",
    textColor: "text-teal-50",
    hoverBgColor: "hover:bg-teal-700",
    outline: `${COMMON.outline} outline-teal-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-teal-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-teal-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-teal-500`,
    scrollbar: `scrollbar scrollbar-teal`,
  },
  GREEN: {
    label: "Green",
    bgColor: "bg-green-600",
    lightBgColor: "bg-green-50",
    textColor: "text-green-50",
    hoverBgColor: "hover:bg-green-700",
    outline: `${COMMON.outline} outline-green-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-green-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-green-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-green-500`,
    scrollbar: `scrollbar scrollbar-green`,
  },
  LIME: {
    label: "Lime",
    bgColor: "bg-lime-600",
    lightBgColor: "bg-lime-50",
    textColor: "text-lime-50",
    hoverBgColor: "hover:bg-lime-700",
    outline: `${COMMON.outline} outline-lime-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-lime-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-lime-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-lime-500`,
    scrollbar: `scrollbar scrollbar-lime`,
  },
  YELLOW: {
    label: "Yellow",
    bgColor: "bg-yellow-600",
    lightBgColor: "bg-yellow-50",
    textColor: "text-yellow-50",
    hoverBgColor: "hover:bg-yellow-700",
    outline: `${COMMON.outline} outline-yellow-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-yellow-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-yellow-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-yellow-500`,
    scrollbar: `scrollbar scrollbar-yellow`,
  },
  AMBER: {
    label: "Amber",
    bgColor: "bg-amber-600",
    lightBgColor: "bg-amber-50",
    textColor: "text-amber-50",
    hoverBgColor: "hover:bg-amber-700",
    outline: `${COMMON.outline} outline-amber-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-amber-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-amber-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-amber-500`,
    scrollbar: `scrollbar scrollbar-amber`,
  },
  ORANGE: {
    label: "Orange",
    bgColor: "bg-orange-600",
    lightBgColor: "bg-orange-50",
    textColor: "text-orange-50",
    hoverBgColor: "hover:bg-orange-700",
    outline: `${COMMON.outline} outline-orange-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-orange-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-orange-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-orange-500`,
    scrollbar: `scrollbar scrollbar-orange`,
  },
  EMERALD: {
    label: "Emerald",
    bgColor: "bg-emerald-600",
    lightBgColor: "bg-emerald-50",
    textColor: "text-emerald-50",
    hoverBgColor: "hover:bg-emerald-700",
    outline: `${COMMON.outline} outline-emerald-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-emerald-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-emerald-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-emerald-500`,
    scrollbar: `scrollbar scrollbar-emerald`,
  },
  SKY: {
    label: "Sky",
    bgColor: "bg-sky-600",
    lightBgColor: "bg-sky-50",
    textColor: "text-sky-50",
    hoverBgColor: "hover:bg-sky-700",
    outline: `${COMMON.outline} outline-sky-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-sky-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-sky-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-sky-500`,
    scrollbar: `scrollbar scrollbar-sky`,
  },
  VIOLET: {
    label: "Violet",
    bgColor: "bg-violet-600",
    lightBgColor: "bg-violet-50",
    textColor: "text-violet-50",
    hoverBgColor: "hover:bg-violet-700",
    outline: `${COMMON.outline} outline-violet-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-violet-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-violet-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-violet-500`,
    scrollbar: `scrollbar scrollbar-violet`,
  },
  FUCHSIA: {
    label: "Fuchsia",
    bgColor: "bg-fuchsia-600",
    lightBgColor: "bg-fuchsia-50",
    textColor: "text-fuchsia-50",
    hoverBgColor: "hover:bg-fuchsia-700",
    outline: `${COMMON.outline} outline-fuchsia-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-fuchsia-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-fuchsia-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-fuchsia-500`,
    scrollbar: `scrollbar scrollbar-fuchsia`,
  },
  ROSE: {
    label: "Rose",
    bgColor: "bg-rose-200",
    lightBgColor: "bg-rose-50",
    textColor: "text-rose-900",
    hoverBgColor: "hover:bg-rose-300",
    outline: `${COMMON.outline} outline-rose-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-rose-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-rose-900/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-rose-500`,
    scrollbar: `scrollbar scrollbar-rose`,
  },
  ZINC: {
    label: "Zinc",
    bgColor: "bg-zinc-400",
    lightBgColor: "bg-zinc-50",
    textColor: "text-zinc-900",
    hoverBgColor: "hover:bg-zinc-300",
    outline: `${COMMON.outline} outline-zinc-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-zinc-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-zinc-50/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-zinc-500`,
    scrollbar: `scrollbar scrollbar-zinc`,
  },
  GRAY: {
    label: "Gray",
    bgColor: "bg-gray-200",
    lightBgColor: "bg-gray-50",
    textColor: "text-gray-900",
    hoverBgColor: "hover:bg-gray-100",
    outline: `${COMMON.outline} outline-gray-500`,
    hoverOutline: `${COMMON.hoverOutline} outline-gray-500`,
    placeholder: `${COMMON.placeholder} placeholder:text-gray-900/30`,
    focusOutline: `${COMMON.focusOutline} focus:outline-gray-500`,
    scrollbar: `scrollbar scrollbar-gray`,
  },
};
